name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
      
    - name: Installing Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12

    - name: Installing surge
      run: npm install --global surge
    
    - name: deploying using surge
      run: surge ./ reactjsbootcamp.surge.sh --token ${{ secrets.SURGE_TOKEN }}